apiVersion: apps/v1
kind: Deployment
metadata:
  name: feedapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: feedapp
  template:
    metadata:
      labels:
        app: feedapp
    spec:
      containers:
      - name: feedapp-container
        image: feedapp:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
      - name: mongodb-container
        image: mongo:latest
        ports:
        - containerPort: 27017
