apiVersion: v1
kind: Service
metadata:
  name: iot-simulation
spec:
  selector:
    app: iot-simulation
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 80
  type: ClusterIP
