
services:
  feedapp:
    image: feedapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/feedappdb
      RABBITMQ_HOST: rabbitmq
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - mongo
      - rabbitmq
      - postgres
      - iot-simulation

  feedapp-frontend:
    image: feedapp-frontend:latest
    build:
      context: ./feedapp-frontend
      dockerfile: Dockerfile
    ports:
      - 4200:80
    depends_on:
      - feedapp

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  iot-simulation:
    image: iot-simulation:latest
    build:
      context: ./iotSimulation
      dockerfile: Dockerfile
    ports:
      - 8000:80
  
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  mongodb_data: {}
  postgres_data: {}
