
services:
  feedapp:
    image: feedapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/feedappdb
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  iot-simulation:
    image: iot-simulation:latest
    build:
      context: ./iotSimulation
      dockerfile: Dockerfile
    ports:
      - 8000:80


volumes:
  mongodb_data:
