
services:
  feedapp:
    image: feedapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/feedappdb
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - mongo
      - rabbitmq

  feedapp-frontend:
    image: feedapp-frontend:latest
    build:
      context: ./feedapp-frontend
      dockerfile: Dockerfile
    ports:
      - 4200:80
    depends_on:
      - feedapp
      - mongo
      - rabbitmq
      - iot-simulation

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db

  iot-simulation:
    image: iot-simulation:latest
    build:
      context: ./iotSimulation
      dockerfile: Dockerfile
    ports:
      - 8000:80
  
  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  mongodb_data:

