name: FeedApp

on:
  push:
    branches: [ "main" , "spring-security"]
  pull_request:
    branches: [ "main" ]

jobs:
  feedapp-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build and Test FeedApp
        run: |
            cd feedapp-2
            mvn --batch-mode --update-snapshots verify
